#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --exclusive
#SBATCH --nodes 2
#SBATCH --time 00:20:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --output d2q9-bgk.out
#SBATCH --exclude compute[100,101,102,103,104,110,111,117,121,127,216,300]

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
#srun --mpi=pmi2 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
#srun --mpi=pmi2 ./d2q9-bgk input_128x256.params obstacles_128x256.dat
#srun --mpi=pmi2 ./d2q9-bgk input_256x256.params obstacles_256x256.dat
#srun --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -n 40 --mpi=pmi2 advixe-cl -collect survey --project-dir ./advisor3 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun -n 40 --mpi=pmi2 advixe-cl -collect tripcounts -flop --project-dir ./advisor3 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
